-- door names
door_names = {
  "parlor", 
  "anteroom", 
  "wardrobe", 
  "wardrobe_balcony", 
  "family_hallway", 
  "hallway_1f", 
  "study", 
  "master_bedroom", 
  "nursery", 
  "twins", 
  "basement_stairwell", 
  "stairwell_2f_w", 
  "stairwell_2f_n", 
  "courtyard_w", 
  "courtyard_e", 
  "bathroom_1f", 
  "conservatory", 
  "billiards", 
  "washroom_1f", 
  "ballroom", 
  "dining", 
  "laundry", 
  "fortune", 
  "rec_room_n", 
  "rec_room_s", 
  "storage", 
  "kitchen", 
  "boneyard", 
  "projection", 
  "mirror", 
  "butler", 
  "tea", 
  "rear_hallway_2f", 
  "bathroom_2f", 
  "washroom_2f", 
  "nana", 
  "astral", 
  "sitting", 
  "safari", 
  "observatory", 
  "guest", 
  "east_attic", 
  "artist", 
  "balcony", 
  "west_attic", 
  "armory", 
  "telephone", 
  "clockwork", 
  "ceramics", 
  "breaker", 
  "cellar", 
  "basement_hallway", 
  "cold", 
  "pipe", --nice
  "spade_hallway", 
  "secret_altar"
}

-- door numer ids
door_numbers = {
  "34",
  "38",
  "43",
  "41",
  "33",
  "3",
  "32",
  "31",
  "27",
  "28",
  "9",
  "74",
  "24",
  "42",
  "25",
  "23",
  "21",
  "17",
  "20",
  "15",
  "14",
  "7",
  "4",
  "25",
  "24",
  "16",
  "11",
  "10",
  "18",
  "5",
  "1",
  "47",
  "75",
  "48",
  "45",
  "49",
  "44",
  "29",
  "56",
  "40",
  "30",
  "55",
  "63",
  "62",
  "59",
  "51",
  "52",
  "53",
  "50",
  "71",
  "68",
  "67",
  "65",
  "69", --nice
  "70",
  "72"
}  

door_keys = {
  ["parlor"] = {name = "parlor", key = "key_parlor"}, 
  ["anteroom"] = {name = "anteroom", key = "key_anteroom"}, 
  ["wardrobe"] = {name = "wardrobe", key = "key_wardrobe"}, 
  ["wardrobe_balcony"] = {name = "wardrobe_balcony", key = "key_wardrobebalcony"}, 
  ["family_hallway"] = {name = "family_hallway", key = "key_famhall"}, 
  ["hallway_1f"] = {name = "hallway_1f", key = "key_heart"}, 
  ["study"] = {name = "study", key = "key_study"}, 
  ["master_bedroom"] = {name = "master_bedroom", key = "key_MasterBed"}, 
  ["nursery"] = {name = "nursery", key = "key_nursery"}, 
  ["twins"] = {name = "twins", key = "key_twin"}, 
  ["basement_stairwell"] = {name = "basement_stairwell", key = "key_basementstair"}, 
  ["stairwell_2f_w"] = {name = "stairwell_2f_w", key = "key_lower2f"}, 
  ["stairwell_2f_n"] = {name = "stairwell_2f_n", key = "key_southrec"}, 
  ["courtyard_w"] = {name = "courtyard_w", key = "key_club"}, 
  ["courtyard_e"] = {name = "courtyard_e", key = "key_northrec"}, 
  ["bathroom_1f"] = {name = "bathroom_1f", key = "key_1fbath"}, 
  ["conservatory"] = {name = "conservatory", key = "key_conservatory"}, 
  ["billiards"] = {name = "billiards", key = "key_billiards"}, 
  ["washroom_1f"] = {name = "washroom_1f", key = "key_1fwash"}, 
  ["ballroom"] = {name = "ballroom", key = "key_ballroom"}, 
  ["dining"] = {name = "dining", key = "key_dining"}, 
  ["laundry"] = {name = "laundry", key = "key_laundry"}, 
  ["fortune"] = {name = "fortune", key = "key_fortune"}, 
  ["rec_room_n"] = {name = "rec_room_n", key = "key_northrec"}, 
  ["rec_room_s"] = {name = "rec_room_s", key = "key_southrec"}, 
  ["storage"] = {name = "storage", key = "key_storage"}, 
  ["kitchen"] = {name = "kitchen", key = "key_kitchen"}, 
  ["boneyard"] = {name = "boneyard", key = "key_boneyard"}, 
  ["projection"] = {name = "projection", key = "key_projection"}, 
  ["mirror"] = {name = "mirror", key = "key_mirror"}, 
  ["butler"] = {name = "butler", key = "key_butler"}, 
  ["tea"] = {name = "tea", key = "key_tea"}, 
  ["rear_hallway_2f"] = {name = "rear_hallway_2f", key = "key_upper2f"}, 
  ["bathroom_2f"] = {name = "bathroom_2f", key = "key_2fbath"}, 
  ["washroom_2f"] = {name = "washroom_2f", key = "key_2fwash"}, 
  ["nana"] = {name = "nana", key = "key_nana"}, 
  ["astral"] = {name = "astral", key = "key_astral"}, 
  ["sitting"] = {name = "sitting", key = "key_sitting"}, 
  ["safari"] = {name = "safari", key = "key_safari"}, 
  ["observatory"] = {name = "observatory", key = "key_observatory"}, 
  ["guest"] = {name = "guest", key = "key_guest"}, 
  ["east_attic"] = {name = "east_attic", key = "key_eastattic"}, 
  ["artist"] = {name = "artist", key = "key_artist"}, 
  ["balcony"] = {name = "balcony", key = "key_balcony"}, 
  ["west_attic"] = {name = "west_attic", key = "key_diamond"}, 
  ["armory"] = {name = "armory", key = "key_armory"}, 
  ["telephone"] = {name = "telephone", key = "key_telephone"}, 
  ["clockwork"] = {name = "clockwork", key = "key_clockwork"}, 
  ["ceramics"] = {name = "ceramics", key = "key_ceramics"}, 
  ["breaker"] = {name = "breaker", key = "key_breaker"}, 
  ["cellar"] = {name = "cellar", key = "key_cellar"}, 
  ["basement_hallway"] = {name = "basement_hallway", key = "key_basehall"}, 
  ["cold"] = {name = "cold", key = "key_cold"}, 
  ["pipe"] = {name = "pipe", key = "key_pipe"}, 
  ["spade_hallway"] = {name = "spade_hallway", key = "key_spadehall"}, 
  ["secret_altar"] = {name = "secret_altar", key = "key_spade"}
}

default_door_locks = {
  [1] = {["parlor"] = 0},
  [2] = {["anteroom"] = 0},
  [3] = {["wardrobe"] = 0},
  [4] = {["wardrobe_balcony"] = 0},
  [5] = {["family_hallway"] = 0},
  [6] = {["hallway_1f"] = 0},
  [7] = {["study"] = 0},
  [8] = {["master_bedroom"] = 0},
  [9] = {["nursery"] = 0},
  [10] = {["twins"] = 0},
  [11] = {["basement_stairwell"] = 0},
  [12] = {["stairwell_2f_w"] = 0},
  [13] = {["stairwell_2f_n"] = 0},
  [14] = {["courtyard_w"] = 0},
  [15] = {["courtyard_e"] = 0},
  [16] = {["bathroom_1f"] = 0},
  [17] = {["conservatory"] = 0},
  [18] = {["billiards"] = 0},
  [19] = {["washroom_1f"] = 0},
  [20] = {["ballroom"] = 0},
  [21] = {["dining"] = 0},
  [22] = {["laundry"] = 0},
  [23] = {["fortune"] = 0},
  [24] = {["rec_room_n"] = 0},
  [25] = {["rec_room_s"] = 0},
  [26] = {["storage"] = 0},
  [27] = {["kitchen"] = 0},
  [28] = {["boneyard"] = 0},
  [29] = {["projection"] = 0},
  [30] = {["mirror"] = 0},
  [31] = {["butler"] = 0},
  [32] = {["tea"] = 0},
  [33] = {["rear_hallway_2f"] = 0},
  [34] = {["bathroom_2f"] = 0},
  [35] = {["washroom_2f"] = 0},
  [36] = {["nana"] = 0},
  [37] = {["astral"] = 0},
  [38] = {["sitting"] = 0},
  [39] = {["safari"] = 0},
  [40] = {["observatory"] = 0},
  [41] = {["guest"] = 0},
  [42] = {["east_attic"] = 0},
  [43] = {["artist"] = 0},
  [44] = {["balcony"] = 0},
  [45] = {["west_attic"] = 0},
  [46] = {["armory"] = 0},
  [47] = {["telephone"] = 0},
  [48] = {["clockwork"] = 0},
  [49] = {["ceramics"] = 0},
  [50] = {["breaker"] = 0},
  [51] = {["cellar"] = 0},
  [52] = {["basement_hallway"] = 0},
  [53] = {["cold"] = 0},
  [54] = {["pipe"] = 0},
  [55] = {["spade_hallway"] = 0},
  [56] = {["secret_altar"] = 0}
}
